services:
  mysql:
    image: mysql:8.4.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - internal
    restart: always

  php:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: php
    volumes:
      - C:\Users\goann\Desktop\DEV\GitHub\la-maison-de-sylvain\prod:/var/www/html
    ports:
      - "8080:80"
    networks:
      - internal
    restart: always

volumes:
  mysql_data:

networks:
  internal:
